### ISSUE TITLE
Improve database versions validation checking

### ISSUE THREAD

**Issue by the-redback** [kubedb/project#122]
- [x] Remove `CheckDockerImageVersion` checking in each db-operator
- [x] Verify db versions by mapping in each db-operator 
- [x] Remove mounted volume for ImagePullSecret in CLI

**Comment by the-redback** [comment]
Fixed
