### ISSUE TITLE
Support custom configuration

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#187]
The general idea is user provides a Configmap / Secret that we mount . 

- [x] Postgres :  https://github.com/kubedb/project/issues/155
- [x] Redis: https://github.com/kubedb/project/issues/114
- [x] MySQL: https://github.com/kubedb/project/issues/188
- [x] Memcache: https://github.com/kubedb/project/issues/189
- [ ] Elasticsearch: https://github.com/kubedb/project/issues/193
