### ISSUE TITLE
Tracking issue: Update doc for release 0.9

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#288]
Update Concept:
- [x] Elasticsearch
- [x] Memcached
- [x] MongoDB
- [x] MySQL
- [x] PostgreSQL
- [x] Redis

Add doc for DBVersion crd:
- [x] Elasticsearch
- [x] Memcached
- [x] MongoDB
- [x] MySQL
- [x] PostgreSQL
- [x] Redis

Update Guides:
- [x] Elasticsearch
- [x] Memcached
- [x] MongoDB
- [x] MySQL
- [x] PostgreSQL
- [x] Redis

Update Examples:
- [x] Elasticsearch
- [x] Memcached
- [x] MongoDB
- [x] MySQL
- [x] PostgreSQL
- [x] Redis

Others:
- [x] Make clear that `wipOut` does not clear snapshot data from local backend. xref: https://github.com/kubedb/project/issues/261
- [x] Fix snapshot backend for local backend. xref: https://github.com/kubedb/project/issues/266
- [x] Document that requests is used for storage resources. xref: https://github.com/kubedb/project/issues/192
- [x] Show how to find available storageclass. xref: https://github.com/kubedb/project/issues/192
- [x] Don't use gitRepo as script source. Use configMap. xref: https://github.com/kubedb/project/issues/170

**Comment by the-redback** [comment]
Update concept:
- [ ] Snapshot
