### ISSUE TITLE
KubeDB: Elasticsearch Documentation Roadmap 

### ISSUE THREAD

**Issue by kamolhasan** [kubedb/project#787]
# KubeDB: Elasticsearch

## Concept: 

- [ ] Internal users
- [ ] Internal role  mapping 
- [ ] SSL for Transport layer & Rest layer
- [ ] User credentials (username & password)
- [ ] Cert secrets management (ca.crt, tls.crt, tls.key)
 
## Guide:

- [ ] Quickstart
  - [ ] with security disabled
  - [ ] with security enabled 

- [ ] Clustering
  - [ ] Standalone 
  - [ ] Topology 

- [ ] SearchGuard
- [ ] OpenDistro
- [ ] X-pack 

- [ ] Custom config
  - [ ] x-pack & elasticsearch.yml
  - [ ] opendistro & elasticsearch.yml
  - [ ] searchguard & elasticsearch.yml

- [ ] Monitoring 
- [ ] TLS setup 
- [ ] Custom Users & role mapping
  - [ ] searchguard 
  - [ ] opendistro
